### ISSUE TITLE
Check conventions for example files

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-json-schemas#12]
- provide 2 files always named "minimum" and "full"

- make sure that "total" property is all examples and evaluate if it should be mandatory as some minimum examples define that.

**Comment by emmenko** [comment]
`total` is just meta information, not mandatory.

**Comment by panshul007** [comment]
done: ) https://github.com/sphereio/sphere-json-schemas/commit/2502264e8ab55bff6607ac3946d26c832e5f18c5
